- name: provisioning
  hosts: all
  become: yes
  gather_facts: False
  
  vars:
    app_path: /vagrant
    home: /home/vagrant
  tasks:
    - name: set timezone to Asia/Tokyo
      timezone:
        name: Asia/Tokyo

    - name: add yum repository
      yum: name="{{ item }}" state=latest
      with_items:
        - epel-release
        - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

    - name: yum basic install
      yum: name="{{ item }}" state=present
      with_items:
        - zip
        - unzip
        - git
        - maven
        - MySQL-python
        - mariadb  
        - mariadb-server

    - name: git clone
      ansible.builtin.git:
        repo: https://github.com/yoshito1124/spring.git
        dest: /home/vagrant/codes
    
    - name: start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: true

    - name: mariadb root user password setting
      mysql_user:
        login_user: "root"
        login_password: ""
        name: "root"
        password: ""
        state: present
        check_implicit_admin: yes

    - name: create database
      mysql_db:
        login_user: "root"
        login_password: ""
        name: "spring-portfolio"
        state: present